# action.yml
name: 'Create labels'
description: 'Create standard labels'
inputs:
  gh_ibm_token:
    description: 'GitHub Oauth Token for IBM'
    required: true
  zenhub_ibm_apikey:
    description: 'ZenHub API Key for IBM'
    required: false
runs:
  using: 'node12'
  main: 'main.js'
